#!/bin/bash
set -e
# 1. Sync the Laravel boilerplate to the host volume if the host is missing the base files
# /var/www_tmp acts as a temporary clean workspace containing the fresh Laravel clone.
# By using `cp -rn` (no clobber), it safely merges the boilerplate into /var/www 
# without overwriting your specialized overlay code (like custom routes or controllers).
if [ ! -f "/var/www/artisan" ]; then
    echo "First run detected! Merging Laravel boilerplate into host volume..."
    cp -rn /var/www_tmp/* /var/www/
    cp -rn /var/www_tmp/.[!.]* /var/www/ 2>/dev/null || true
fi
# 2. Proceed with database wait
echo "Waiting for database..."
until (echo > /dev/tcp/mysql/3306) &>/dev/null; do
    sleep 2
done
echo "Database is ready."
# 3. Handle Missing Assets and Migrations
# (Breeze is now handled directly inside PHPDockerfile, so its controllers 
# and routes are already present inside /var/www_tmp and safely copied over!)

if [ ! -f "/var/www/public/build/manifest.json" ]; then
    echo "Vite manifest missing! Rebuilding frontend assets..."
    npm install && npm run build
fi

php artisan migrate

# 4. Fix permissions
# All files generated by root during this startup script (artisan, npm, composer) 
# must be owned by www-data so the PHP-FPM workers can access them.
chown -R www-data:www-data /var/www

# 5. Start PHP-FPM
php-fpm