services:
  app:
    build:
      context: .
      dockerfile: PHPDockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./routes:/var/www/routes
      - assets_data:/var/www/public/build
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - assets_data:/var/www/public/build
    depends_on:
      - app
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
  assets_data: