server {
    listen 80;
    server_name your_domain.com; # Replace with your domain or IP

    root /var/www/public; # Replace with your web root directory
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string; 
    }

    location ~ \.php$ {
        include fastcgi_params; # Includes common FastCGI parameters
        fastcgi_pass app:9000; # Passes requests to the docker container named app on localhost port 9000
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Optional: Deny access to .ht* files if you are also using Apache rules
    location ~ /\.ht {
        deny all;
    }
}
